In [8]:
! python train_model.py --train_path=matres/relations/sample_train.txt --epochs=2 --lr=0.01 --batch=8 --output_file=temp_en_version1 --save_model=temp_model_1 --test_path=matres/relations/sample_test.txt --dev_path=matres/relations/sample_test.txt

EPOCH: 0 ########## Train Loss: 1.3752021789550781
Val loss: 0.1111111111111111 ----- Val Micro F1: 0.1111111111111111 Val Macro F1: 0.049999999999999996


EPOCH: 1 ########## Train Loss: 1.359562873840332
Val loss: 0.1111111111111111 ----- Val Micro F1: 0.1111111111111111 Val Macro F1: 0.049999999999999996


Model configuration: MLP with SGD Optimizer, model name: temp_model_1, loss file: temp_en_version1

LR: 0.01, Epochs: 2 Batch: 8

We are using 2 consequtive sentences per event where possible
concatenating the cls token as well


Accuracy: 0.1111111111111111 micro-F1: 0.1111111111111111 macro-F1: 0.049999999999999996

----Confusion Matrix-----
[[0 6 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]]
Output (losses) saved as file: ../output_files/temp_en_version1.csv
model saved as file: ../saved_models/temp_model_1
Class weights: tensor([0.4906, 0.7750, 7.6154, 1.8526], device='cuda:0')


Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.dense.bias']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [15]:
! python train_model.py --train_path=matres/relations_2_sentences/train_sample.txt --epochs=2 --lr=0.01 --batch=8 --output_file=temp_en_version1 --save_model=temp_model_1 --test_path=matres/relations_2_sentences/test_sample.txt --dev_path=matres/relations/sample_test.txt

EPOCH: 0 ########## Train Loss: 1.3712854385375977
Val loss: 0.1111111111111111 ----- Val Micro F1: 0.1111111111111111 Val Macro F1: 0.049999999999999996


EPOCH: 1 ########## Train Loss: 1.3656128644943237
Val loss: 0.1111111111111111 ----- Val Micro F1: 0.1111111111111111 Val Macro F1: 0.049999999999999996


Model configuration: MLP with SGD Optimizer, model name: temp_model_1, loss file: temp_en_version1

LR: 0.01, Epochs: 2 Batch: 8

We are using 2 consequtive sentences per event where possible
concatenating the cls token as well


Accuracy: 0.0 micro-F1: 0.0 macro-F1: 0.0

----Confusion Matrix-----
[[0 3 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]]
Output (losses) saved as file: ../output_files/temp_en_version1.csv
model saved as file: ../saved_models/temp_model_1
Class weights: tensor([0.4906, 0.7750, 7.6154, 1.8526], device='cuda:0')


Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [13]:
! python train_model.py --train_path=matres/relations/train_timebank.txt --epochs=10 --lr=0.1 --output_file=version1 --save_model=model_1 --test_path=matres/relations/test_platinum.txt

^C


In [2]:
! python train_model.py --train_path=EN/train_v2.txt --epochs=100 --lr=0.01 --output_file=en_version2 --save_model=en_model_v2

Epoch: 0 ########## Train Loss: 1.3650566339492798, Train Acc: 0.59375

Epoch: 1 ########## Train Loss: 1.367709755897522, Train Acc: 0.5

Epoch: 2 ########## Train Loss: 1.3460633754730225, Train Acc: 0.59375

Epoch: 3 ########## Train Loss: 1.3607317209243774, Train Acc: 0.40625

Epoch: 4 ########## Train Loss: 1.3442292213439941, Train Acc: 0.53125

Epoch: 5 ########## Train Loss: 1.3294134140014648, Train Acc: 0.53125

Epoch: 6 ########## Train Loss: 1.343810796737671, Train Acc: 0.4375

Epoch: 7 ########## Train Loss: 1.352225422859192, Train Acc: 0.40625

Epoch: 8 ########## Train Loss: 1.2964842319488525, Train Acc: 0.59375

Epoch: 9 ########## Train Loss: 1.3133196830749512, Train Acc: 0.5

Epoch: 10 ########## Train Loss: 1.2863720655441284, Train Acc: 0.59375

Epoch: 11 ########## Train Loss: 1.3013889789581299, Train Acc: 0.5

Epoch: 12 ########## Train Loss: 1.28575599193573, Train Acc: 0.53125

Epoch: 13 ########## Train Loss: 1.2522449493408203, Train Acc: 0.59375

Epoch:

Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
d:\ML_Projects\RUG_Research_Training\event_anchorability\src\BertTempRel.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return nn.functional.softmax(x)
d:\ML_Projects\RUG_Research_Training\event_anchorability\src\BertTempRel.py

In [95]:
import torch
from transformers import AutoTokenizer, XLMRobertaModel, XLMRobertaTokenizer
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base", return_tensors='pt')
model = XLMRobertaModel.from_pretrained("xlm-roberta-base", output_hidden_states=False, output_attentions=False)
#tokenizer = XLMRobertaModel("xlm-roberta", return_tensors='pt')

Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.dense.weight', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.bias']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [116]:
X= "I am Loving it 's --- test U.S. jet ."
encodings = tokenizer(X, truncation=True, padding=True, return_tensors='pt')

In [117]:
len(encodings['input_ids'][0])

19

In [108]:
model.eval()
outputs = model (**encodings)

In [109]:
encodings['input_ids']

tensor([[    0,    87,   444, 39701,   214,   442, 28229,  3034,     2]])

In [110]:
outputs.last_hidden_state.shape

torch.Size([1, 9, 768])

In [66]:
encodings['attention_mask']

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [118]:
tokenizer.convert_ids_to_tokens(encodings['input_ids'][0])

['<s>',
 '▁I',
 '▁am',
 '▁Lov',
 'ing',
 '▁it',
 "▁'",
 's',
 '▁---',
 '▁test',
 '▁U',
 '.',
 'S',
 '.',
 '▁je',
 't',
 '▁',
 '.',
 '</s>']

In [1]:
from customDataHandler import customDataset
import torch
from transformers import AutoTokenizer, XLMRobertaModel
from BertTempRel import BertTempRel
path = 'D:/ML_Projects/RUG_Research_Training/event_anchorability/dataset/EN/samples_3.txt'
train_dataset= customDataset(path=path)

from torch.utils.data import DataLoader
dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True)

#model = XLMRobertaModel.from_pretrained("xlm-roberta-base")

#device = 'cuda' if torch.cuda.is_available() else 'cpu'
device = 'cpu'
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base", return_tensors='pt')

model = BertTempRel()
model = model.to(device)
#optimizier = torch.optim.SGD(params=model.parameters(), lr=0.1)
for batch in dataloader:
    input_ids = batch['input_ids']
    attention_mask = batch['attention_mask']
    loc1 = batch['location1']
    loc2 = batch['location2']
    input_ids = input_ids.to(device)
    attention_mask= attention_mask.to(device)
    loc1 = loc1.to(device)
    loc2 = loc2.to(device)
    #print(type(input_ids))
    #outputs = model(input_ids, attention_mask=attention_mask)
    outputs = model(input_ids, attention_mask=attention_mask, event1 = loc1, event2 =loc2 )
    

c:\Users\DELL\anaconda3\envs\py3.10\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
d:\ML_Projects\RUG_Research_Training\event_anchorab

In [2]:
outputs

tensor([[0.2565, 0.2346, 0.2531, 0.2557],
        [0.2560, 0.2382, 0.2553, 0.2505],
        [0.2585, 0.2321, 0.2561, 0.2533]], grad_fn=<SoftmaxBackward0>)

In [3]:
model.parameters()
optimizier = torch.optim.SGD(params=list(model.parameters()), lr=0.1)

In [9]:
outputs.argmax(dim=1)

tensor([3, 3, 3])

In [13]:
outputs[0][0].shape

torch.Size([33, 768])

In [5]:
from BertTempRel import BertTempRel
from transformers import AutoTokenizer, XLMRobertaModel
model = BertTempRel()
#model = XLMRobertaModel.from_pretrained("xlm-roberta-base")
print(model.parameters())

Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


<generator object Module.parameters at 0x0000021B1A72FBC0>


In [14]:
from transformers import AutoTokenizer, XLMRobertaModel
import torch

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
model = XLMRobertaModel.from_pretrained("xlm-roberta-base")

inputs = tokenizer("one.. . two ", return_tensors="pt")
model.eval()
outputs = model(inputs['input_ids'], inputs['attention_mask'])


Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.dense.bias', 'lm_head.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [15]:
inputs['input_ids']

tensor([[   0, 1632,    5,    5,    6,    5, 6626,    2]])

In [21]:
"one.. . two".split()

['one..', '.', 'two']

In [8]:
outputs.last_hidden_state.shape

torch.Size([1, 7, 768])

mdeberta-v3-base

In [6]:
from transformers import AutoTokenizer, DebertaV2Model
import torch
model_name = "microsoft/mdeberta-v3-base"
tokenizer = AutoTokenizer.from_pretrained(model_name,  use_fast=False)
model = DebertaV2Model.from_pretrained(model_name)
inputs = tokenizer("Hello, my dog is doing cute", return_tensors="pt")
outputs = model(**inputs)
last_hidden_states = outputs.last_hidden_state


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Some weights of the model checkpoint at microsoft/mdeberta-v3-base were not used when initializing DebertaV2Model: ['mask_predictions.LayerNorm.bias', 'lm_predictions.lm_head.bias', 'mask_predictions.LayerNorm.weight', 'mask_predictions.dense.weight', 'mask_predictions.classifier.bias', 'mask_predictions.dense.bias', 'lm_predictions.lm_head.dense.weight', 'lm_predictions.lm_head.LayerNorm.weight', 'lm_predictions.lm_head.dense.bias', 'lm_predictions.lm_head.LayerNorm.bias', 'deberta.embeddings.word_embeddings._weight', 'mask_predictions.classifier.weight']
- This IS expected if you are initializing DebertaV2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaV2Model from the checkpoint of a

In [7]:
tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])

['[CLS]', '▁Hello', ',', '▁my', '▁dog', '▁is', '▁do', 'ing', '▁cute', '[SEP]']

## TENSOR operations if they are working fine or not

In [1]:
import torch

locs1 = [1, 4, 2]
locs2 = [5, 7, 4]
t1 = torch.Tensor([[ [2,3,1,5], [11,12,13,14], [2,3,1,5], [11,12,13,14], [1,6,4,5],[101,102, 103,104], [1,6,4,5],[101,102, 103,104] ],
                   [ [1,6,4,5],[101,102, 103,104], [1,6,4,5],[101,102, 103,104], [2,3,1,5], [11,12,13,14], [2,3,1,5], [11,12,13,14], ],
                   [ [1,9,8,0],[601,602,603,604], [1,9,8,0],[601,602,603,604], [2,3,1,5], [11,12,13,14], [2,3,1,5], [11,12,13,14],   ] ])
t2 = torch.Tensor([ [ [10,1,11,12], [33,32,34,77], [10,1,11,12], [33,32,34,77], [17,18,19,20],[61,62,63,78], [17,18,19,20],[61,62,63,78]  ],
                    [ [13,14,15,16], [42,43,41,78],[13,14,15,16], [42,43,41,78], [10,1,11,12], [33,32,34,77], [10,1,11,12], [33,32,34,77]  ],
                    [ [17,18,19,20],[61,62,63,78], [17,18,19,20],[61,62,63,78], [13,14,15,16], [42,43,41,78],[13,14,15,16], [42,43,41,78]  ] ])


In [2]:
t1.shape

torch.Size([3, 8, 4])

In [9]:
t2[0, 1:3 , :]

tensor([[33., 32., 34., 77.],
        [10.,  1., 11., 12.]])

In [27]:
complete_tensor= torch.empty(0,2*4)
for i in range(len(locs1)):
    l1= locs1[i]
    l2 = locs2[i]
    tok1 = torch.mean(t1[i, 0 : l1, :], dim =0)
    tok2 = torch.mean(t2[i, l1 : l2, :], dim =0)
    print(type(tok1))
    print(type(tok2))
    tok = torch.cat((tok1,tok2), dim =0 )
    complete_tensor = torch.vstack((complete_tensor, tok))
print(complete_tensor)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
tensor([[  2.0000,   3.0000,   1.0000,   5.0000,  23.2500,  20.7500,  24.5000,
          46.5000],
        [ 51.0000,  54.0000,  53.5000,  54.5000,  17.6667,  11.3333,  18.6667,
          33.6667],
        [301.0000, 305.5000, 305.5000, 302.0000,  39.0000,  40.0000,  41.0000,
          49.0000]])


### MERGE Tensors

In [54]:
list1=[0 , 1, 1]
t= torch.cat((t1[[i for i in range(3)], list1], t2[[i for i in range(3)], list1]), 1)
t

tensor([[  2.,   3.,   1.,   5.,  10.,   1.,  11.,  12.],
        [101., 102., 103., 104.,  42.,  43.,  41.,  78.],
        [601., 602., 603., 604.,  61.,  62.,  63.,  78.]])

## CHECKING IF THE DATALOADER IS WORKING FINE OR NOT

In [2]:
from customDataHandler import customDataset
path = 'D:/ML_Projects/RUG_Research_Training/event_anchorability/dataset/EN/samples_3.txt'
train_dataset= customDataset(path=path)

In [3]:
train_dataset

In [3]:
from torch.utils.data import DataLoader
dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True)

In [5]:
for (idx, batch) in enumerate(dataloader):

    # Print the 'text' data of the batch
    print(idx, 'Sentence 1: ', batch['sentence1'])
    print(idx, 'Sentence 2: ', batch['sentence2'])
    print(idx, 'Event 1: ', batch['location1']) 
    print(idx, 'Event 2: ', batch['location2'])
    # Print the 'class' data of batch
    print(idx, 'Label ', batch['label'], '\n')

0 Sentence 1:  ['People have predicted his demise so many times , and the US has tried to hasten it on several occasions . [SEP]', 'People have predicted his demise so many times , and the US has tried to hasten it on several occasions . [SEP]', 'People have predicted his demise so many times , and the US has tried to hasten it on several occasions . [SEP]']
0 Sentence 2:  ['People have predicted his demise so many times , and the US has tried to hasten it on several occasions .', 'People have predicted his demise so many times , and the US has tried to hasten it on several occasions .', 'People have predicted his demise so many times , and the US has tried to hasten it on several occasions .']
0 Event 1:  tensor([2, 2, 2])
0 Event 2:  tensor([37, 26, 35])
0 Label  tensor([3, 0, 3]) 



In [6]:
from transformers import AutoTokenizer, XLMRobertaModel
import torch

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
model = XLMRobertaModel.from_pretrained("xlm-roberta-base")

for (idx, batch) in enumerate(dataloader):

    # Print the 'text' data of the batch
    print(idx, 'Sentence 1: ', batch['sentence1'])
    print(idx, 'Sentence 2: ', batch['sentence2'])
    batch['location1'] +=1
    print(len(batch['sentence1'][0]))
    for i in range(len(batch['label'])):
        batch['location2'][i] += len(batch['sentence1'][i])
    print(idx, 'Event 1: ', batch['location1']) 
    print(idx, 'Event 2: ', batch['location2'])
    # Print the 'class' data of batch
    print(idx, 'Label ', batch['label'], '\n')



inputs = tokenizer("one two three four five", return_tensors="pt")
model.eval()
outputs = model(**inputs)

Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


0 Sentence 1:  ['People have predicted his demise so many times , and the US has tried to hasten it on several occasions .', 'People have predicted his demise so many times , and the US has tried to hasten it on several occasions .', 'People have predicted his demise so many times , and the US has tried to hasten it on several occasions .']
0 Sentence 2:  ['People have predicted his demise so many times , and the US has tried to hasten it on several occasions .', 'People have predicted his demise so many times , and the US has tried to hasten it on several occasions .', 'People have predicted his demise so many times , and the US has tried to hasten it on several occasions .']
105
0 Event 1:  tensor([3, 3, 3])
0 Event 2:  tensor([109, 120, 118])
0 Label  tensor([0, 3, 3]) 



In [2]:
! python train_model.py --epochs=3

model size: 1061.036MB


Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaModel: ['lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.dense.bias']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
d:\ML_Projects\RUG_Research_Training\event_anchorability\src\BertTempRel.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return nn.functional.softmax(x)
Traceback (most recent call last):
  File "d:\ML_Projects\RUG_Research_Trai

In [9]:
!python prompt_LLM.py --model meta-llama/Meta-Llama-3-8B-Instruct --test_dir matres/relations_2_sentences/test_sample.txt --prompt_dir prompts/four_shot.txt

meta-llama/Meta-Llama-3-8B-Instruct
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to C:\Users\DELL\.cache\huggingface\token
Login successful


c:\Users\DELL\anaconda3\envs\py3.10\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Loading checkpoint shards: 100%|██████████| 4/4 [00:59<00:00, 14.97s/it]
Traceback (most recent call last):
  File "d:\ML_Projects\RUG_Research_Training\event_anchorability\src2\prompt_LLM.py", line 121, in <module>
    main()
  File "d:\ML_Projects\RUG_Research_Training\event_anchorability\src2\prompt_LLM.py", line 105, in main
    pipe = pipeline('text-generation', model=model, tokenizer=tokenizer, device=device)
  File "c:\Users\DELL\anaconda3\envs\py3.10\lib\site-packages\transformers\pipelines\__init__.py", line 1108, in pipeline
    return pipeline_class(model=model, fra

In [8]:
!python prompt_LLM.py --test_dir matres/relations/test_platinum.txt --prompt_dir prompts/four_shot.txt --n_shot=4

google/flan-t5-small
EQUAL


Token indices sequence length is longer than the specified maximum sequence length for this model (686 > 512). Running this sequence through the model will result in indexing errors
c:\Users\DELL\anaconda3\envs\py3.10\lib\site-packages\transformers\generation\configuration_utils.py:515: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
c:\Users\DELL\anaconda3\envs\py3.10\lib\site-packages\transformers\generation\configuration_utils.py:537: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `10` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(


In [ ]:
!python prompt_LLM.py --model meta-llama/Meta-Llama-3-8B-Instruct --test_dir matres/relations_2_sentences/test_sample.txt --prompt_dir prompts/four_shot.txt --n_shot=4